export { AppComponent } from './app.component'
export { HomeComponent } from './home/home.component'
export { NavbarComponent } from './navbar/navbar.component'
export { LoginComponent } from './login/login.component'
export { RegisterComponent } from './register/register.component'
export { ProfileComponent } from './profile/profile.component'